### PR TITLE
Remove SVDIR from environment if it was set

### LINKED ISSUE #51: Unset/reset SVDIR
This is where https://github.com/chef/chef-server/issues/1075 should be solved. 😉

### PR DESCRIPTION
**Pull request by srenatus**
Fixes #51.

### CODE REVIEW

**Comment by matthiasr** [comment]
We also use runit outside of the omnibus package, and it seems that omnibus-ctl is using the wrong `sv` binary at times. `chef-server-ctl reconfigure` works, but `chef-server-ctl status` and `restart` require `SVDIR=/opt/opscode/service` for us:

```
% sudo chef-server-ctl status
fail: bookshelf: unable to change to service directory: file does not exist
fail: nginx: unable to change to service directory: file does not exist
fail: oc_bifrost: unable to change to service directory: file does not exist
fail: oc_id: unable to change to service directory: file does not exist
fail: opscode-erchef: unable to change to service directory: file does not exist
fail: opscode-expander: unable to change to service directory: file does not exist
fail: opscode-solr4: unable to change to service directory: file does not exist
fail: postgresql: unable to change to service directory: file does not exist
fail: rabbitmq: unable to change to service directory: file does not exist
fail: redis_lb: unable to change to service directory: file does not exist
% sudo env SVDIR=/opt/opscode/service chef-server-ctl status
run: bookshelf: (pid 23938) 5777s; run: log: (pid 995) 20211517s
run: nginx: (pid 24137) 5777s; run: log: (pid 994) 20211517s
run: oc_bifrost: (pid 23619) 5780s; run: log: (pid 989) 20211517s
run: oc_id: (pid 23704) 5779s; run: log: (pid 999) 20211517s
run: opscode-erchef: (pid 24028) 5777s; run: log: (pid 992) 20211517s
run: opscode-expander: (pid 23870) 5778s; run: log: (pid 991) 20211517s
run: opscode-solr4: (pid 23714) 5779s; run: log: (pid 996) 20211517s
run: postgresql: (pid 1025) 20211517s; run: log: (pid 993) 20211517s
run: rabbitmq: (pid 1005) 20211517s; run: log: (pid 990) 20211517s
run: redis_lb: (pid 24070) 89s; run: log: (pid 997) 20211517s
```

This PR will probably break this workaround … how can we keep using omnibus and runit?

**Comment by srenatus** [comment]
> ... omnibus-ctl is using the wrong sv binary at times. 

This would be a bug. Could you have a closer look _at which times_ this happens in your system?

Chef-Server's use of runit should not mess with yours.

**Comment by matthiasr** [comment]
It happens on those commands that are directly passed through to runit. I dug a bit deeper and will file a separate issue.

**Comment by srenatus** [comment]
@matthiasr thanks!

**Pull request merged**
