### PR TITLE
Embedded chef-client runs must be stateless

### PR DESCRIPTION
**Pull request by sean-horn**

### CODE REVIEW

**Comment by smith** [comment]
Won't this break show-config for anything who's cookbook is not called `private-chef`?

**Comment by sean-horn** [comment]
@smith Good point about things without the cookbook name "private-chef" . Thanks for the update.

**Comment by sean-horn** [comment]
@smith Manage has its own omnibus-ctl in /opt/opscode-manage/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb for at least Manage 1.11.0 which still uses chef-solo.

**Comment by mmzyk** [comment]
@sean-horn I believe @smith's point is that this repo, omnibus-ctl, is a shared repo across all the projects that have a ctl command. Therefore any changes here are expected to work across every project. While projects maybe pinned to an older version, eventually they will update at some point and pull in any updates here, so this repo can't reference anything that is specific to a certain project.

That means any change that references a private-chef cookbook has to be done in the opscode-omnibus repo or if this is a change that needs to be made to this repo it needs to be done in a way that will work for all projects or if that can't be done then we need to coordinate with all projects to update.  

What is driving this change and perhaps we can work out a solution that fits for everyone?

**Comment by smith** [comment]
In order for this to work correctly we would need a way to supply the cookbook name (especially since, in the case of Chef server, it is not the same as the install path or project name ("opscode" or "chef-server-core" or whatever.)

Not sure about the best way to pass this in. A typical x-ctl command wrapper looks like this:

https://github.com/chef/opscode-omnibus/blob/438cf5a0f32a940a34e35264c8fac6d0073f9e98/config/software/private-chef-ctl.rb#L59

where the service name and a path to additional commands to be loaded are given as arguments, which are loaded by the omnibus-ctl executable:

https://github.com/chef/omnibus-ctl/blob/80e44976c7f6b9dab8188f7f74b742254c1d8943/bin/omnibus-ctl

Anybody on @chef/server-team have opinions on the best way to handle passing in the cookbook name or fixing this issue in general?

**Comment by stevendanna** [comment]
@mmzyk @smith To answer an earlier question,

> What is driving this change and perhaps we can work out a solution that fits for everyone?

The issue with the node state being saved to disk is that it is read on the next reconfigure.  This can lead to situations where (because of how we load the config) a user removes a configuration value from their config file, but the relevant configuration isn't reverted to the default on a reconfigure. This likely affects most add-ons that merge their config into the node object and then use that throughout the cookbooks.

> Anybody on @chef/server-team have opinions on the best way to handle passing in the cookbook name or fixing this issue in general?

Is chef-server-12 the only project where the "name" that we pass into omnibus-ctl is different from the underlying cookbook name?  If so, maybe it would be easiest to just change the name of that cookbook in chef-server and then use "recipe[#{name}::default]" as the cookbook name.

**Comment by smith** [comment]
@stevendanna I know that right now in Manage the "name" is opscode-manage and the cookbook is called opscode-manage, but in work I'm doing right now the name is "chef-manage" and the cookbook is "omnibus-manage", because there's a "chef-manage" cookbook that is used outside of the package. We could change this, but it seems like a pretty rigid assumption that has proven to be problematic.

**Comment by stevendanna** [comment]
@smith I'm not tied t that idea, but I would like to find a solution on the side of convention over configuration.

**Comment by sean-horn** [comment]
I could make an interim patch to cover all products which just reads from the content of the config files, like https://github.com/chef/omnibus-manage/blob/master/config/software/opscode-manage-cookbooks.rb#L29-L43 , as those filenames are fixed, but with differing contents per product?

**Comment by stevendanna** [comment]
@sh @smith I've posted an alternative here https://github.com/chef/omnibus-ctl/pull/27 that simply nukes the saved node state. Because we shipped this in chef-server, we need something that nukes that node state anyway for existing installs.

**Pull request closed without merging**
